spring:
  application:
    name: user-service

  logging:
    level:
      org.hibernate.tool.schema: DEBUG
      org.hibernate.SQL: DEBUG
      org.hibernate.type.descriptor.sql: TRACE
      org.springframework.orm.jpa: DEBUG

  profiles:
    active: dev

  kafka:
    bootstrap-servers: localhost:9092

    consumer:
      group-id: user-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.type.mapping: "com.example.arena_service.event.MatchFinishedEvent:com.example.event.MatchFinishedEvent"

server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus

  endpoint:
    prometheus:
      enabled: true

  metrics:
    enable:
      kafka: true
    tags:
      application: ${spring.application.name}