input {
  tcp {
    port => 5000
    codec => json_lines
  }
}

filter {
  mutate {
    add_field => {
      "ambiente" => "desenvolvimento"
      "stack" => "arena-system"
    }
  }
}

output {
  stdout {
    codec => rubydebug
  }
}